# Create or recreate android/app/sms-gateway-release.keystore and android/signing.properties.
param(
    [string]$StorePassword,
    [string]$KeyPassword,
    [string]$KeyAlias = "smsgateway"
)

$ErrorActionPreference = "Stop"
$root = Join-Path $PSScriptRoot ".."
$androidDir = Join-Path $root "android"
$keystorePath = Join-Path $androidDir "app\sms-gateway-release.keystore"
$signingPath = Join-Path $androidDir "signing.properties"

if (-not $StorePassword) {
    $secure = Read-Host "Keystore password" -AsSecureString
    $StorePassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    )
}
if (-not $KeyPassword) {
    $KeyPassword = $StorePassword
}

if (Test-Path $keystorePath) {
    $overwrite = Read-Host "Keystore already exists. Overwrite? (y/N)"
    if ($overwrite -notmatch '^[Yy]') {
        Write-Host "Aborted. Update android/signing.properties with your existing keystore password instead."
        exit 0
    }
    Remove-Item $keystorePath -Force
}

& keytool -genkeypair -v -storetype PKCS12 `
    -keystore $keystorePath `
    -alias $KeyAlias `
    -keyalg RSA -keysize 2048 -validity 10000 `
    -storepass $StorePassword `
    -keypass $KeyPassword `
    -dname "CN=SMS Gateway, OU=Dev, O=ScrapRegos, L=Tashkent, ST=Tashkent, C=UZ"

@"
# Generated by scripts/setup-release-signing.ps1 — do not commit.
STORE_FILE=app/sms-gateway-release.keystore
STORE_PASSWORD=$StorePassword
KEY_ALIAS=$KeyAlias
KEY_PASSWORD=$KeyPassword
"@ | Set-Content -Path $signingPath -Encoding ASCII

Write-Host "Created:"
Write-Host "  $keystorePath"
Write-Host "  $signingPath"
Write-Host ""
Write-Host "Build release APK with: npm run android:apk:release"
